name: EconomyPack
version: '${project.version}'
main: pawel.cookier.ignaczak.economypack.EconomyPack
api-version: '1.20'
commands:
  shop:
    description: Opens shop
    permission: EconomyPack.shop
  add_shop_category:
    description: Adds new category to shop
    permission: EconomyPack.add_shop_category
  remove_shop_category:
    description: Removes category from shop
    permission: EconomyPack.remove_shop_category
  edit_shop_category_name:
    description: Changes category name
    permission: EconomyPack.edit_shop_category_name
  edit_shop_category_icon:
    description: Changes category icon
    permission: EconomyPack.edit_shop_category_icon
  add_shop_item:
    description: Adding item to category
    permission: EconomyPack.add_shop_item
  add_item_from_hand:
    description: Adds item from hand to category
    permission: EconomyPack.add_item_from_hand
  edit_item_sell_price:
    description: Changes item sell price
    permission: EconomyPack.edit_item_sell_price
  edit_item_buy_price:
    description: Changes item buy price
    permission: EconomyPack.edit_item_buy_price
  gamble:
    description: Play gamble game
    permission: EconomyPack.gamble
  slots:
    description: Play slots game
    permission: EconomyPack.slots
  exchange:
    description: Exchange gold ingots to money
    permission: EconomyPack.exchange
  pay:
    description: Pay player
    permission: EconomyPack.pay
  translation:
    description: Changes the language of the plugin.
    permission: EconomyPack.translation
  permissions:
    EconomyPack.translation:
      description: Allows the player to change the plugin language.
      default: op
    EconomyPack.money_new:
      description: Allows to add player to database manually.
      default: op